Features/13 add signmessage for registration
We-Are-Swissborg/WASB-Front pull request #15
Opened 2024-05-27 16:53 UTC by KeotiseuF

2024-05-27 17:29 UTC, Valdior commented
Sorry, identique avec l'autre PR, je ne fais pas la diff....
Ca sort du context du ticket :(

2024-06-03 19:30 UTC, Valdior requested changes

2024-06-03 19:30 UTC, Valdior commented on src/services/test.services.ts
> +    const response: Response = await fetch(`${backend}api/test/withoutAuth`, options);
cette partie devrait être en conflit avec la branch develop maintenant.
Désolé je t'ai pris de cours sur cette partie :(

2024-06-03 19:30 UTC, Valdior commented on src/hook/Form.tsx
>  interface IAuth {
IAuth n'a rien à faire dans le form.tsx
le status est un attribut par défaut des Response. Si tu as dû le créer, c'est que t'as logique n'est pas bonne.

2024-06-03 19:30 UTC, Valdior commented on src/web3/SignMessage.ts
> +        const pathname = window.location.pathname;
Pas moyen d'utilisée le router pour savoir où on se trouve plutôt que ce système ?

2024-06-04 08:28 UTC, KeotiseuF commented on src/hook/Form.tsx
>  interface IAuth {
Je voulais éviter de créer un fichier pour si peu de ligne et le statut j'étais obligé de l'initialisé car avec le typage j'ai une erreur, 'reponse' peut pas être un objet nul si je me trompe pas

2024-06-04 08:28 UTC, KeotiseuF commented on src/web3/SignMessage.ts
> +        const pathname = window.location.pathname;
Surement avec le hook useLocation (useLocation.pathname) mais cela change quoi ?

2024-06-05 11:01 UTC, Valdior requested changes

2024-06-05 11:01 UTC, Valdior commented on src/web3/SignMessage.ts
> +        const pathname = window.location.pathname;
Parce que ca respect les outils et convention de l'outil qu'on utilise

2024-06-08 02:27 UTC, closed without merging

2024-06-08 02:28 UTC, KeotiseuF commented
Ferme cette PR car une autre méthode est utilisé