#30 Loading page
We-Are-Swissborg/WASB-Front pull request #31
Opened 2024-07-01 18:35 UTC by Valdior

* add loading global page (auth)
* add loading to blog
* add swc (call API : https://swr.vercel.app/fr-FR/docs/getting-started)
* add Toast Notification

2024-07-01 22:56 UTC, KeotiseuF requested changes

2024-07-01 22:56 UTC, KeotiseuF commented on src/contexts/LoadingContext.tsx
Faudrait mettre les commentaires en anglais stp 😄

2024-07-01 22:56 UTC, KeotiseuF commented on src/App.tsx
A quoi sert le ToastContainer, il me semble qu'il n'est pas utilisé ?

2024-07-02 07:10 UTC, Valdior commented on src/App.tsx
voilà un exemple : https://github.com/We-Are-Swissborg/WASB-Front/pull/31/commits/605861cb7ae2b3c0d602658e3416dc4e7c461fad

2024-07-02 08:23 UTC, KeotiseuF approved these changes

2024-07-02 08:23 UTC, KeotiseuF approved these changes

2024-07-02 08:24 UTC, KeotiseuF approved these changes

2024-07-02 08:24 UTC, merged