log after register
We-Are-Swissborg/WASB-Front pull request #48
Opened 2024-07-23 12:58 UTC by KeotiseuF

2024-07-23 13:22 UTC, Valdior requested changes

2024-07-23 13:22 UTC, Valdior commented on src/component/Security/Register.tsx
> -    // Comment être sur que sera toujours 5 comme valeur ?
pourquoi retirer ce commentaire ? il a tout son sens.

Si dans 5 mois, on decide de passer à 8 caractères, comment fait-on ?

2024-07-23 13:22 UTC, Valdior commented on src/component/Security/Register.tsx
> +                localStorage.setItem('codeRef', `${value}`);
pourquoi placer dans le localstorage une valeur qui est sensé être en validation ? 
L'intérêt de garder en mémoire le code, c'est sur on passe par l'url

2024-07-23 13:22 UTC, Valdior commented on src/component/Security/Register.tsx
> +        return false;
Pourquoi cette option plus que celle existante ?

2024-07-23 13:24 UTC, Valdior commented
Bref, beaucoup de question autour de cet évènement de validation...
Du coup je me pose la question de si c'est vraiment le meilleur de faire ?
Déjà il passe dans cette méthode a plus sieurs moment de son cycle (entré/sortie de l'input, peut-être d'autres également)

2024-07-23 13:51 UTC, KeotiseuF commented on src/component/Security/Register.tsx
> -    // Comment être sur que sera toujours 5 comme valeur ?
Ah mince, je voulais le mettre en anglais

2024-07-23 13:57 UTC, KeotiseuF commented on src/component/Security/Register.tsx
> +                localStorage.setItem('codeRef', `${value}`);
C'est toi qui m'avait demandé si j'ai bien compris que si l'utilisateur rentrait un referral valide et que s'il quittait la page entre-temps, qu'on puisse retrouver le referral dans le champs

2024-07-23 14:01 UTC, KeotiseuF commented on src/component/Security/Register.tsx
> +        return false;
Pour accepter le fait que si la valeur revienne à 0 alors on peut envoyer le formulaire sinon on aurait pas pu car cela renverrait false ce qui bloquerai la validation du champs

2024-07-23 14:13 UTC, KeotiseuF commented
> Bref, beaucoup de question autour de cet évènement de validation... Du coup je me pose la question de si c'est vraiment le meilleur de faire ? Déjà il passe dans cette méthode a plus sieurs moment de son cycle (entré/sortie de l'input, peut-être d'autres également)

C'est exactement ce que je t'ai dis le jour où tu m'avais demandé cette validation

2024-07-23 14:49 UTC, Valdior commented on src/component/Security/Register.tsx
> +                localStorage.setItem('codeRef', `${value}`);
Heu.... non, seulement depuis l'url comme tu l'avais fais précédemment. C'est amplement suffisant

2024-07-23 14:52 UTC, Valdior commented
> > Bref, beaucoup de question autour de cet évènement de validation... Du coup je me pose la question de si c'est vraiment le meilleur de faire ? Déjà il passe dans cette méthode a plus sieurs moment de son cycle (entré/sortie de l'input, peut-être d'autres également)
> 
> C'est exactement ce que je t'ai dis le jour où tu m'avais demandé cette validation

Alors je t'ai mal compris...

Est-ce qu'on va faire une requête a chaque changement : Oui

1. ACD00
2. AAA33
3. S4D6E

Est-ce qu'on va faire plusieurs la même requête pour rien : non

![image](https://github.com/user-attachments/assets/9d18b8bd-76df-43c5-ad2b-d434f2692631)

2024-07-24 14:04 UTC, Valdior approved these changes

2024-07-24 14:13 UTC, merged