Features/5 user profile
We-Are-Swissborg/WASB-Front pull request #56
Opened 2024-07-31 13:04 UTC by KeotiseuF

2024-08-01 07:46 UTC, Valdior requested changes

2024-08-01 07:46 UTC, Valdior commented on src/component/Form/AccountForm.tsx
> +    const [init, setInit] = useState(true);
la convention pour les booleans est de mettre un is ou has devant.
isInit dans ce cas

2024-08-01 07:46 UTC, Valdior commented on src/component/Form/MembershipForm.tsx
> +    const [valueMembership, setValueMembership] = useState<Membership>({
pas besoin de mettre les valeurs par défault ici si tu les mets également dans le initUser

2024-08-01 07:46 UTC, Valdior commented on src/component/Form/MembershipForm.tsx
> +        console.log("Ça t'amuse d'enlever les disabled :D");
J'imagine la prise de tête :)

2024-08-01 07:46 UTC, Valdior commented on src/component/Profile.tsx
> +export default function Profil() {
Non, Profile en anglais :)

2024-08-01 07:46 UTC, Valdior commented on src/component/Profile.tsx
> +    const linkedAccountClas = choiceSetting === 4 ? 'btn-secondary text-white' : 'bg-secondary-subtle text-black';
tiens, je t'avais pas fait un remarque avec ce code redondant :)

2024-08-01 08:27 UTC, KeotiseuF commented on src/component/Form/AccountForm.tsx
> +        const value = e.target.value;
Je sais, je trouve sa plus esthétique 😄 Et de plus si plus tard, j'ai besoin de la valeur, je sais que j'ai une variable dédiée pour

2024-08-01 08:28 UTC, KeotiseuF commented on src/types/Membership.ts
> +    endDateContribution?: Date | null;
Ah oui 😅

2024-08-01 08:29 UTC, KeotiseuF commented on src/services/user.service.ts
> +const updateUser = async (id: number, token: string, data: User | SocialMedias): Promise<User> => {
C'est un oublie merci 😅

2024-08-01 08:34 UTC, KeotiseuF commented on src/component/Form/MembershipForm.tsx
> +    const [valueMembership, setValueMembership] = useState<Membership>({
Oui, j'avais une erreur, je ne savais pas la résoudre mais enfaite c'est bon, j'avais la solution depuis le début 😆

2024-08-01 08:35 UTC, KeotiseuF commented on src/component/Form/MembershipForm.tsx
> +        console.log("Ça t'amuse d'enlever les disabled :D");
J'hésitez entre ça ou un appel à venir nous aidez 🤣

2024-08-01 08:36 UTC, KeotiseuF commented on src/component/Profile.tsx
> +export default function Profil() {
Oh merci j'avais même pas fais attention pourtant le fichier il est bon

2024-08-01 08:39 UTC, KeotiseuF commented on src/component/Profile.tsx
> +    const linkedAccountClas = choiceSetting === 4 ? 'btn-secondary text-white' : 'bg-secondary-subtle text-black';
Oui je sais je t'ai pas oublié 😉 mais comme je t'ai dis vu que c'était déjà en place et que ça fonctionne, je reviendrais dessus après 😄

2024-08-01 10:16 UTC, KeotiseuF commented on src/types/Membership.ts
> +    endDateContribution?: Date | null;
En fait, c'est "undefined" qui est accepté, pas "null", d'où les null. Je vais les enlever et mettre "undefined" aux variables concernées.

2024-08-02 06:32 UTC, Valdior requested changes

2024-08-02 06:32 UTC, Valdior commented on src/services/socialMedias.service.ts
> +const updateSocialMediasUser = async (userId: number, token: string, data: SocialMedias): Promise<undefined> => {
C'est bizarre ca, une promise undefined o_O

2024-08-02 06:32 UTC, Valdior commented on src/types/Account.ts
Curiosité, mais pourquoi refaire un type Account alors que le user contient déjà tous ces champs ?

2024-08-02 07:18 UTC, KeotiseuF commented on src/services/socialMedias.service.ts
> +const updateSocialMediasUser = async (userId: number, token: string, data: SocialMedias): Promise<undefined> => {
La pour le coup je savais pas quoi mettre, je reçois pas de réponse, d'où le undefined

2024-08-02 07:23 UTC, KeotiseuF commented on src/types/Account.ts
Y a des champs qu'on doit remplir obligatoirement, j'en ai pas besoin...

2024-08-02 07:43 UTC, Valdior commented on src/services/socialMedias.service.ts
> +const updateSocialMediasUser = async (userId: number, token: string, data: SocialMedias): Promise<undefined> => {
la réponse est dans le status
Si 204 return que ca passe, donc true
Si pas 204 alors tu sais qu'il y a une erreur, retourne le message d'erreur

2024-08-02 08:25 UTC, KeotiseuF commented on src/services/socialMedias.service.ts
> +const updateSocialMediasUser = async (userId: number, token: string, data: SocialMedias): Promise<undefined> => {
Non, ça je sais. Mais enfaite, je n'avais pas vu que j'avais un bug car je t'ai dit, je recevais pas de réponse bah maintenant je comprends mieux pourquoi 😞 
![image](https://github.com/user-attachments/assets/c74a4e31-bb36-4b68-954f-ce3a811f2cd9)

2024-08-06 07:11 UTC, Valdior approved these changes

2024-08-06 08:25 UTC, Valdior approved these changes

2024-08-06 09:28 UTC, merged