#59 feat: admin manage users
We-Are-Swissborg/WASB-Front pull request #60
Opened 2024-08-14 11:59 UTC by Valdior

2024-08-14 19:42 UTC, KeotiseuF requested changes
Faudrait ajouter un toast pour signaler l'ajout d'un rôle et aussi vérifier pourquoi le toast.info lorsque rien n'a changé s'active, quand on va sur un user admin le toast s'active tout le temps. 

Peux-tu rajouter un recherche sur les rôles comme tu as fait avec les autres colonnes ? stp

Et une dernière chose, qui ne semble pas vraiment avoir d'impact, c'est plus à titre informatif tu as l'erreur 'key should unique' qui s'affiche qu'à l'initialisation de la liste des users, sur le premier utilisateur au niveau de son rôle.

2024-08-15 09:03 UTC, Valdior commented
> Faudrait ajouter un toast pour signaler l'ajout d'un rôle et aussi vérifier pourquoi le toast.info lorsque rien n'a changé s'active, quand on va sur un user admin le toast s'active tout le temps.
> 
> Peux-tu rajouter un recherche sur les rôles comme tu as fait avec les autres colonnes ? stp
> 
> Et une dernière chose, qui ne semble pas vraiment avoir d'impact, c'est plus à titre informatif tu as l'erreur 'key should unique' qui s'affiche qu'à l'initialisation de la liste des users, sur le premier utilisateur au niveau de son rôle.

En effet, j'ai bien remarqué ce problème avec les toasts dans l'admin. Je ne me suis pas concentrer dessus pour le moment.
Pour la recherche, j'ai essayé mais pas réussit, 

Je vais regarder pour le key should unique

2024-08-15 14:21 UTC, KeotiseuF commented
> > Faudrait ajouter un toast pour signaler l'ajout d'un rôle et aussi vérifier pourquoi le toast.info lorsque rien n'a changé s'active, quand on va sur un user admin le toast s'active tout le temps.
> > Peux-tu rajouter un recherche sur les rôles comme tu as fait avec les autres colonnes ? stp
> > Et une dernière chose, qui ne semble pas vraiment avoir d'impact, c'est plus à titre informatif tu as l'erreur 'key should unique' qui s'affiche qu'à l'initialisation de la liste des users, sur le premier utilisateur au niveau de son rôle.
> 
> En effet, j'ai bien remarqué ce problème avec les toasts dans l'admin. Je ne me suis pas concentrer dessus pour le moment. Pour la recherche, j'ai essayé mais pas réussit,
> 
> Je vais regarder pour le key should unique

Il y a toujours l'erreur de la key mais cette fois lorsque l'on va édit un utilisateur et les réseaux sociaux ne s'affichent pas côté administrateur, socialMediasRef est undefined.

Et il manque le toast lorsque l'on modifie un rôle, en tout cas quelque chose pour signaler le changement

2024-08-15 21:21 UTC, Valdior commented
L'erreur ne vient pas de ce que j'ai fait, mais des problèmes existant sans les prendre en considérations dans tes changements.
(je te laisse chercher un peu d'où cela vient, tu devrais les trouver assez rapidement)

Avoir un toast qui apparait a chaque changement de rôle me parait plus embêtant qu'autre chose en tant qu'admin, c'est la raison pour la quelle je ne l'ai pas appliqué

2024-08-21 14:54 UTC, KeotiseuF commented
> L'erreur ne vient pas de ce que j'ai fait, mais des problèmes existant sans les prendre en considérations dans tes changements. (je te laisse chercher un peu d'où cela vient, tu devrais les trouver assez rapidement)
> 
> Avoir un toast qui apparait a chaque changement de rôle me parait plus embêtant qu'autre chose en tant qu'admin, c'est la raison pour la quelle je ne l'ai pas appliqué

Pourtant je l'ai pas dans la section profile cette erreur 🤔 Je dois finir le blog, et j'aimerai bien mettre en place la partie newsletter une fois finis 😃

Je comprends c'est pourquoi je conseillé une alternative car lorsque l'on coche, on n'a pas l'impression qu'on fait une requête mais que cela fais partie du formulaire alors que non.

2024-08-28 10:57 UTC, merged

2024-08-30 14:34 UTC, KeotiseuF commented
L'erreur avait était résolue ?