Review blog and add display post
We-Are-Swissborg/WASB-Front pull request #61
Opened 2024-08-14 12:41 UTC by KeotiseuF

1. Ajout des cards pour la partir blog.
2. Création des posts avec vérification des champs.
3. Ajout d'une preview avant la création du post.

Il manque la pagination, le design, la traduction, la suppression/update d'un post, la validation des autres admin ou modo et le filtrage des posts 

NO MERGE FOR THE MOMENT

2024-08-14 13:48 UTC, Valdior requested changes

2024-08-14 13:48 UTC, Valdior commented on src/services/baseAPI.services.ts
Pas d'accord sur le principe, si tu le retires le 'Content-Type' à la source, pourquoi faire un delete apres  dans ta méthode ? 
Surtout si c'est pour l'ajouter après dans chaque autres méthodes.

Si tu fais un delete, remplace le par un autre content-type plus adapter, il faut garder la sécurité sur ce que tu envois

2024-08-14 19:46 UTC, KeotiseuF commented on src/component/OnePost.tsx
J'ai mis onePost car cela crée une erreur de nom, avec le fichier de typage pour les posts

2024-08-14 19:49 UTC, KeotiseuF commented on src/component/Route/ProtectedRouter.tsx
C'est pour accepter plusieurs rôles sur 1 routes, cela ressemble à ce que tu as fais au niveau du back sur la PR d'aujourd'hui

2024-08-14 21:28 UTC, KeotiseuF commented on src/services/baseAPI.services.ts
J'ai cette erreur : https://stackoverflow.com/questions/49692745/express-using-multer-error-multipart-boundary-not-found-request-sent-by-pos

2024-08-15 10:50 UTC, Valdior commented on src/component/Route/ProtectedRouter.tsx
Mais je ne vois pas pourquoi ce changement, un rôle est suffisant vu que c'est hierarchique

2024-08-15 10:54 UTC, Valdior commented on src/component/OnePost.tsx
Renomme le Article dans ce cas, c'est moche OnePost... :(

2024-08-15 10:54 UTC, Valdior commented on src/services/baseAPI.services.ts
Ca ne répond pas à la question..

2024-08-15 14:48 UTC, KeotiseuF commented on src/services/baseAPI.services.ts
Parce que l'on utilise FormData, il va s'en occuper si je me trompe pas (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_FormData_Objects). Je le supprime car il me transforme ma donnée en JSON et si je le déclare avec le MIME multipart j'ai l'erreur ci-dessus.

2024-08-15 15:16 UTC, KeotiseuF commented on src/services/baseAPI.services.ts
![image](https://github.com/user-attachments/assets/9fbb7202-a5b6-403b-a15b-7f9c30a5941f)

Malgré le delete le content-type est bien paramétré.
![image](https://github.com/user-attachments/assets/2ef6e28c-2097-43da-9b77-e22aa46d1f37)

2024-08-15 16:15 UTC, Valdior commented on src/services/baseAPI.services.ts
> -requestHeaders.set('Content-Type', 'application/json');
là tu le retires

2024-08-15 16:15 UTC, Valdior commented on src/services/baseAPI.services.ts
> +    requestHeaders.set('Content-Type', 'application/json');
là tu l'ajoutes

2024-08-15 16:15 UTC, Valdior commented on src/services/baseAPI.services.ts
> +    requestHeaders.set('Content-Type', 'application/json');
là tu l'ajoutes

2024-08-15 16:15 UTC, Valdior commented on src/services/baseAPI.services.ts
> +    requestHeaders.delete('Content-Type'); // Not set with multipart/form-data
là tu le retires.
Maintenant relis ma question principale... Je comprend le problème de mime, c'est ton code que je capte pas

2024-08-15 17:13 UTC, KeotiseuF commented on src/services/baseAPI.services.ts
> +    requestHeaders.delete('Content-Type'); // Not set with multipart/form-data
Ah ok, je comprends mieux excuse. Je l'avais mis de cette manière car je n'avais pas le bon content-type une fois passer dans le fetch avec le delete mais enfaite ça fonctionne, c'est bon j'ai remis comme c'était 😉

2024-08-21 15:13 UTC, KeotiseuF commented on src/services/baseAPI.services.ts
> +    requestHeaders.delete('Content-Type'); // Not set with multipart/form-data
En fait, je les ai remis car, une fois passées dans une requête avec un fichier, le content-type n'est pas le même. Alors, il faut redéclarer un content-type pour les autres requêtes, sinon on va avoir une anomalie.

2024-08-25 19:58 UTC, Valdior requested changes
Discuter avec sur DIscord

2024-09-01 18:24 UTC, Valdior commented
tu as toujours des erreurs eslint, le merge est refusé

2024-09-03 07:01 UTC, Valdior approved these changes

2024-09-03 07:14 UTC, merged