Add metrics
We-Are-Swissborg/WASB-Front pull request #80
Opened 2024-11-26 04:19 UTC by KeotiseuF

Add metrics page and get metrics data

2024-11-26 11:57 UTC, Valdior requested changes

2024-11-26 11:57 UTC, Valdior commented on src/assets/images/back-arrow.png
pourquoi de nouveaux icone alors qu'on utilise déjà une bibliotheque pour en avoir ?

2024-11-27 19:09 UTC, KeotiseuF commented on src/component/Metrics.tsx
> +            navigate('/metrics/', {replace: true});
Mince j'avais fusionné 2 fonctions, j'avais pas fais attention au catch

2024-11-27 19:19 UTC, KeotiseuF commented on src/assets/images/back-arrow.png
Je savais pas je regarderai

2024-12-07 13:23 UTC, Valdior approved these changes

2024-12-08 03:36 UTC, merged